easy_admin:
  design:
    menu:
      - { label: app.sidebar.main }
      - { entity: Import, label: app.sidebar.import, icon: file-upload }
      - { entity: Product, label: app.sidebar.product, icon: shopping-basket }
      - { entity: Category, label: app.sidebar.category, icon: th-list }
      - { entity: Offer, label: app.sidebar.offer, icon: layer-group }
      - { entity: Admin, label: app.sidebar.admin, icon: user }
      - { entity: Actionlog, label: app.sidebar.actionlog, icon: clipboard-list }